name: Deploy

on:
  push:
    # for the develop branch only.
    branches:
      - main

jobs:
  semantic-release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_release_version: ${{ steps.tag.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Prepare prerelease semantic
        if: github.ref != 'refs/heads/main'
        run: mv .releaserc.prerelease.yaml .releaserc.yaml

      - name: Semantic Release
        if: github.event.head_commit.message != 'version update'
        uses: cycjimmy/semantic-release-action@v2
        id: semantic # Need an `id` for output variables
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/changelog@5
            @semantic-release/exec@5
            @semantic-release/git@9
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        id: tag
        run: |
          echo 'new_release_version=${{steps.semantic.outputs.new_release_version}}' >> $GITHUB_OUTPUT

  update-versions:
    needs: [semantic-release]
    name: Update Version Files
    runs-on: ubuntu-latest
    if: github.event.head_commit.message != 'version update'
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: output
        run: |
          echo '${{toJSON(needs.semantic-release.outputs.new_release_version)}}'

      - name: Update client file versions
        uses: jaywcjlove/github-action-package@main
        with:
          path: client/package.json
          data: |
            {
              "version": "${{ needs.semantic.outputs.new_release_version }}"
            }
      - name: Update client file versions
        uses: jaywcjlove/github-action-package@main
        with:
          path: server/package.json
          data: |
            {
              "version": "${{ needs.semantic.outputs.new_release_version }}"
            }

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'chart/Chart.yaml'
          propertyPath: 'appVersion'
          value: '${{ needs.semantic-release.outputs.new_release_version }}'
          masterBranchName: main
          targetBranch: main
          branch: main

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'chart/Chart.yaml'
          propertyPath: 'version'
          value: '${{ needs.semantic-release.outputs.new_release_version }}'
          masterBranchName: main
          targetBranch: main
          branch: main

      - name: Commit files
        if: github.event.head_commit.message != 'version update'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add .
          git commit -m 'version update'

      - name: Push changes
        if: github.event.head_commit.message != 'version update'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: main
