name: Unit Tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Repo
        uses: action/checkout@v3
      - name: Install dependencies
        run: |
          cd client
          npm ci
      - name: Run Tests
        run: |
          cd client
          npm test
