name: Unit Tests
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Repo
        uses: action/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
